# _config.yml

title: Harvard HCI Reading Group
description: The weekly reading group for the Harvard HCI group and friends.

content:
  footer: Harvard HCI
  type: Fridays at 2:30pm @ SEC 2.330
  logo:
    alt: Harvard Human-Computer Interaction Logo
    img: https://iis.seas.harvard.edu/wp-content/uploads/2024/12/Harvard-HCI-Logo.png
    url: https://hci.seas.harvard.edu

permalink: pretty

remote_theme: ritesh-kanchi/axya@main

plugins:
  - jekyll-remote-theme
